### ISSUE TITLE
Mapbox Search iOS is returning wrong coordinates for two addresses in New York City

### ISSUE THREAD

**Issue by szewah** [mapbox/mapbox-search-ios#120]
There's an issue with the coordinates for two addresses in New York City. I am asking here because the issues I raised via Mapbox forms hasn't been answered. At all. I sent it over a month ago. 

The two locations are:

**1. Fairway Market at 2131 Broadway, New York City.**
Your coordinates are CLLocationCoordinate2D(latitude: 40.78059768676758, longitude: -73.98127746582031)

It returns this, a location opposite Fairways Market, at the Beacon Theater.

<img width="981" alt="Fairway" src="https://github.com/mapbox/mapbox-search-ios/assets/32065713/11f3121b-cd96-4841-8fd8-1d4d4a0133ff">

**Open Street Maps** [coordinates are correct](https://www.openstreetmap.org/node/1011407273).

**Mapbox playground** [coordinates are correct](https://docs.mapbox.com/playground/search-box/?q=Fairway+Mar&language=en&session_token=0ad20461-5ee5-4b51-888b-b021de60a5ea&access_token=pk.eyJ1Ijoic3dnciIsImEiOiJja2syanQ1MW8wZWdiMnZsNDRqeHVvOW9nIn0.uJzTvCYgZRHCYWXY9JZ19A).

**2. A Tempo at 290 Columbus Ave, New York City**

Your coordinates: CLLocationCoordinate2D(latitude: 40.778621673583984, longitude: -73.97816467285156)

It returns this, a location south of the address. 

<img width="1105" alt="A Tempo" src="https://github.com/mapbox/mapbox-search-ios/assets/32065713/3a2fe41d-f6ce-4631-809b-10c252e3e9ec">

**Open Street Maps** is [correct](https://www.openstreetmap.org/node/2745436354).

**Mapbox playground** doesn't even [bring it up](https://docs.mapbox.com/playground/search-box/?q=A+Tempo&language=en&session_token=0ad20461-5ee5-4b51-888b-b021de60a5ea&access_token=pk.eyJ1Ijoic3dnciIsImEiOiJja2syanQ1MW8wZWdiMnZsNDRqeHVvOW9nIn0.uJzTvCYgZRHCYWXY9JZ19A).

**What I'm using:**

iOS: Ventura 13.4
Mapbox Search iOS: v1.0.0-rc.4
Mapbox Maps: 10.13.1

The piece of code I'm using to query: 

```
func resultResolved(result: SearchResult, searchEngine: SearchEngine) {
           let annotation = CLLocationCoordinate2D(latitude: result.coordinate.latitude, longitude: 
          result.coordinate.longitude)
          print(annotation)
}
```

What's happening here?

**Comment by kalbaxa** [comment]
thanks for posting!

@kried @sarochych can we investigate the difference with the playground?

**Comment by kried** [comment]
Hi @szewah 

It looks like you've been using the raw `SearchEngine` As a general rule, we recommend using `PlaceAutocomplete` API to find a POI. Please, check [our demo app](https://github.com/mapbox/mapbox-search-ios/blob/main/Sources/Demo/PlaceAutocompleteMainViewController.swift) to test the requests. 

---

I checked the response in the SDK for the provided examples. Both of them seem correct. Please share the request and code example so we can check the request options. 

1. For the first query `"Fairway Mar"`, `PlaceAutocomplete` returns the result with `CLLocationCoordinate2D(latitude : 40.7808461, longitude : -73.9817346)` and the routable point  for navigation `CLLocationCoordinate2D(latitude : 40.78075476035471, longitude : -73.98159278446235)`.
  
<img src="https://github.com/mapbox/mapbox-search-ios/assets/3630656/7c22aa54-dde1-42a2-b09c-dae5eea9f903" width="200" />


2. For the second request, Mapbox playground returns the result for the `"A Tempo"` query if the [proximity](https://docs.mapbox.com/playground/search-box/?q=A+Tempo&language=en&proximity=-73.99715283397572,40.81273262438819&session_token=0b538cf6-0615-4c18-88be-a3efc40f9ed7) or bbox are provided.  `"A Tempo"` is quite a general query, in order to find the specific POI you should limit the search area 

The SDK returns the result with `CLLocationCoordinate2D(latitude : 40.778978, longitude : -73.978117)` and the routable point  for navigation `CLLocationCoordinate2D(latitude : 40.778765137546486, longitude : -73.9778402788104)`.

<img alt="Playground" width="200"  src="https://github.com/mapbox/mapbox-search-ios/assets/3630656/4854630a-3b6c-4ff4-9939-6c3463a30903" />

**Comment by szewah** [comment]
Wanted to check - is Place Autofill still in private preview mode? I'm looking at the pricing page and there isn't any information on it. Thanks.

**Comment by kalbaxa** [comment]
@szewah Address Autofill is publicly available and it's pricing is here: https://www.mapbox.com/pricing/#autofill-session

**Comment by szewah** [comment]
So I'll use the address autofill in place of PlaceAutocomplete as per the above example. That should be okay for POI as well. Okay, I'll give it a go.

**Comment by kalbaxa** [comment]
@szewah Address Autofill has different purpose (filling in the address components) and will not provide best POI results.

If you need Place Autocomplete as per example use case in our docs, you can use it without contacting sales. We will update the docs soon. It will definitely have better POIs.

**Comment by szewah** [comment]
Thanks!

**Comment by szewah** [comment]
@kried I'm using PlaceAutocomplete  and the coordinates for the two locations raised in the question are returning correct. Thanks.
