### ISSUE TITLE
Search Chinese keywords with no results

### ISSUE THREAD

**Issue by zhaoyuntian** [mapbox/mapbox-search-ios#41]
Search Chinese keywords with no results

**Comment by zhaoyuntian** [comment]
？？

**Comment by sarochych** [comment]
Hi @zhaoyuntian,
Could you please provide us with more details about your keywords? In general, I was able to retrieve some results using Chinese (Simplified/Traditional) keywords, screenshot attached.

Looking forward for your reply!

![Screenshot 2022-04-13 at 13 01 00](https://user-images.githubusercontent.com/41087911/163154619-68a4d85b-9938-479e-af98-f4f32eab0e5b.png)

**Comment by zhaoyuntian** [comment]
<img width="704" alt="截屏2022-04-14 13 19 38" src="https://user-images.githubusercontent.com/16586931/163318926-dec30e3d-064b-49f3-8e0e-e6f7fb633e63.png">
<img width="319" alt="截屏2022-04-14 13 18 47" src="https://user-images.githubusercontent.com/16586931/163318933-e578c64c-a19a-47ee-9e16-79a11b1e2324.png">
pod 'MapboxSearch', ">= 1.0.0-beta", "< 2.0"

**Comment by zhaoyuntian** [comment]
> Hi @zhaoyuntian, Could you please provide us with more details about your keywords? In general, I was able to retrieve some results using Chinese (Simplified/Traditional) keywords, screenshot attached.
> 
> Looking forward for your reply!
> 
> ![Screenshot 2022-04-13 at 13 01 00](https://user-images.githubusercontent.com/41087911/163154619-68a4d85b-9938-479e-af98-f4f32eab0e5b.png)

**Comment by sarochych** [comment]
@zhaoyuntian thanks for the screenshot, now it is more clear what you're trying to achieve!

Just a note: SearchSDK is still in beta and some API may change, since it isn't final. Also, some API has lack of documentation from our side for the moment and that is your case.

So, according to the screenshot, you use `CategorySearchEngine` and pass custom query as a `categoryName`.

Unfortunately, `CategorySearchEngine` doesn't allow to pass custom queries. In order to make it work we expect concrete category name. Here is a link to all category identifiers currently supported (all categories under an expanded section, screenshot attached):
https://docs.mapbox.com/api/search/geocoding/#point-of-interest-category-coverage

**We will definitely improve API and documentation, hope this helps for the moment!**

<img width="969" alt="Screenshot 2022-04-14 at 14 11 32" src="https://user-images.githubusercontent.com/41087911/163379746-33fa2745-d072-48a8-9279-7d50c3a710bf.png">

**Comment by zhaoyuntian** [comment]
@sarochych. 
<img width="985" alt="截屏2022-04-14 20 33 26" src="https://user-images.githubusercontent.com/16586931/163391451-bae8566f-57b8-4718-af21-b24b0e28c3da.png">
![Uploading 截屏2022-0
<img width="1153" alt="截屏2022-04-14 20 31 02" src="https://user-images.githubusercontent.com/16586931/163391450-0e9460ac-9a1b-4d64-bd41-3fa80a832c28.png">
4-14 20.31.45.png…]()
This  @property.   proximity and origin. is not work，can't get nearby info

**Comment by zhaoyuntian** [comment]
<img width="1037" alt="截屏2022-04-14 20 31 45" src="https://user-images.githubusercontent.com/16586931/163392224-ddf180d2-eb84-49f6-8344-4e1907bb44cf.png">

**Comment by zhaoyuntian** [comment]
<img width="1153" alt="截屏2022-04-14 20 31 02" src="https://user-images.githubusercontent.com/16586931/163392287-e4fdb5e4-b9c4-4291-8dc3-0486af72e87e.png">

**Comment by sarochych** [comment]
@zhaoyuntian it is a bit inconvenient to copy data from screenshot.
Could you please provide us with text version of coordinates (origin) and your search query?
Thanks in advance!

**Comment by zhaoyuntian** [comment]
This key “体育”。 coordinates < lat="39.972499" lon="116.383987">@sarochych

**Comment by sarochych** [comment]
@zhaoyuntian thank you!
I'll check the case, will keep you posted.

**Comment by kalbaxa** [comment]
@zhaoyuntian unfortunately, we do not currently have a committed timeline to improve addresses in China and we plan on adding more than basic POI dataset by the end of year.
