### ISSUE TITLE
Search Result details

### ISSUE THREAD

**Issue by JanTG1** [mapbox/mapbox-search-ios#48]
Is it possible to change the way Search results are displayed? In the attached example it could be difficult to find what you are looking for without knowing what city the place is in. This becomes especially important when searching for rather common road names. In Germany for example, Bahnhofssraße, Schlossstraße, or Universitätsstraße exist in every city, sometimes even multiple times. The Search results sometimes give weird results and the distance is only a small indicator to know which one to select. I'd like to display what city the place is in or with POI the address below the name like it is done with favorites. How can that be achieved? 

![IMG_6091](https://user-images.githubusercontent.com/92864392/169099688-4bfb5659-b038-45e4-aa72-898cd4567825.PNG)

**Comment by JanTG1** [comment]
Hello @sarochych,
thanks for replying. When are you expecting to release the new version which will completely rework the search ios? Seems like there will be large changes, I might want to wait before doing anything important if it's all going to be changed anyway!

I hope the rework will make the search as good as other parts of Mapbox because right now it seems to be lacking behind from what I can see.

**Comment by sarochych** [comment]
Hi @JanTG1,

First of all, a few words about upcoming changes in Search SDK. We are going to rebuild the SDK based on use cases.
In a few weeks we will share our roadmap in the public repo in order to present our plans regarding Search SDK and upcoming feature updates before moving from Beta to GA.

I can provide you with a small example of what use case means in our terms related to Search:
Address Autofill - https://www.mapbox.com/address-autofill

In GA we are going to have a couple of use cases, for example: Address Autofill, Place Autocomplete, Reverse Geocoding.
Some of the use cases will have pre-defined UI.
Our goal is to build modern, convenient and well-documented API.

Regarding our timelines:
- Q3 2022 (July): release our first use case - Address Autofill.
- Q3 2022 (September): rebuild all existing functionality in SearchCore as use cases (Place Autocomplete, Reverse Geocoding)
- Q4 2022 (December): provide pre-defined UI modules for some of the use cases (Place Autocomplete, Address Autofill)

One more thing:
Looks like you have difficulties while using Search SDK. So, we’d be grateful if you could share your feedback about using Search SDK.
We’d like to know all in details 🙂

Thans in advance!
